### ISSUE TITLE
请问下这几个jar包是放在哪呢？

### ISSUE THREAD

**Issue by Decandy-star** [SW-Fantastic/Reader#3]
org.swdc:fx:1.0-SNAPSHOT
org.swdc.fx:deploy:1.0-SNAPSHOT
net.sourceforge.cpdetector:cpdetector:1.0.7
org.swdc.fx:resource:1.0-SNAPSHOT
org.swdc.fx:aop:1.0-SNAPSHOT
org.swdc.fx:jpa:1.0-SNAPSHOT

**Comment by SW-Fantastic** [comment]
是说什么时候放那？org.swdc.fx这些需要你去我其他的几个仓库clone之后用maven给install到本地的maven，然后就可以使用了，net.sourceforge.cpdetector:cpdetector:1.0.7这个也是maven的，准备好之后使用maven更新project就可以。

**Comment by SW-Fantastic** [comment]
如果是说在打包的时候的话，你可以在target目录的libs里面看到他们：
![image](https://user-images.githubusercontent.com/36193170/108845808-d2a12180-7618-11eb-94f7-47b0cdb7fe8e.png)

具体的打包步骤可以参照这里：https://zhuanlan.zhihu.com/p/346312142
其他几个org.swdc.fx的位置：https://github.com/SW-Fantastic/FXApplication，
clone之后分别install里面的几个maven工程就可以得到了。

**Comment by SW-Fantastic** [comment]
然后这个FXApplication的工程，快要结束了，因为我在做一个新的Application环境框架，以后还会用他换掉现在Reader的FXApplication环境。
